name: ${project.name}
version: ${project.version}
description: '${project.description}'
author: Programie
website: ${project.url}
api-version: 1.13
main: com.selfcoders.nearbyrespawner.NearbyRespawner
